pipeline {
  agent any

  stages {
    stage('Cleanup Workspace') {
      steps {
        cleanWs()
      }
    }
    stage("Docker Tag") {
      steps {
        sh "echo ${DOCKERTAG}"
      }
    }
  }
}