pipeline {
  agent any

  stages {
      stage('Cleanup Workspace') {
        steps {
          cleanWs()
        }
      }
      stage('Git Check Out') {
        steps {
          checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'GITHUB_ACCESS_TOKENS', url: 'https://github.com/Anmewzaa/COMSCI_PROJECT_RESTAURANT_K8S']])
        }
      }
      stage('Update Helm Manifest File') {
            steps {
                sh('''
                  sed -i 's/tag: .*/tag: '${DOCKERTAG}'/' k8s/my-project-dev/values.yaml
                ''')
            }
      }
  }
}