pipeline {
  agent any

  environment {
      HOST_NAME = 'asia-southeast1-docker.pkg.dev'
      PROJECT_ID = 'proven-citizen-429506-e2'
      REGISTRY_NAME = 'project-registry'
      IMAGE_NAME = 'project'
  }

  stages {
      stage('Cleanup Workspace') {
        steps {
          cleanWs()
        }
      }
      stage('Git Check Out') {
        steps {
          checkout scmGit(branches: [[name: '*/dev']], extensions: [], userRemoteConfigs: [[credentialsId: 'Github-Token', url: 'https://github.com/Anmewzaa/COMSCI_PROJECT_RESTAURANT_APP']])
        }
      }
      stage('OWASP Dependency-Check Vulnerabilities') {
        steps {
          dependencyCheck additionalArguments: ''' 
                      -o './'
                      -s './'
                      -f 'ALL' 
                      --prettyPrint''', odcInstallation: 'OWASP-CHECK'
          dependencyCheckPublisher pattern: 'dependency-check-report.xml'
        }
      }
      stage('Build and Push Docker Images') {
        steps {
          script {
            env.VERSION = "v0.1.${BUILD_NUMBER}"
            sh('''
                sudo docker build -t ${HOST_NAME}/${PROJECT_ID}/${REGISTRY_NAME}/${IMAGE_NAME}:${VERSION} ./project/
                sudo docker push ${HOST_NAME}/${PROJECT_ID}/${REGISTRY_NAME}/${IMAGE_NAME}:${VERSION}
              ''')
          }
        }
      }
      stage('Trivy Image scan') {
          steps {
            sh('''
              sudo trivy image ${HOST_NAME}/${PROJECT_ID}/${REGISTRY_NAME}/${IMAGE_NAME}:${VERSION} --output trivy_report.html
            ''')
          }
      }
  }
}